version: '3'

services:
  load_balancer:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - private_network
    depends_on:
      - app_server1
      - app_server2

  app_server1:
    build:
      context: ./app_server1
    volumes:
      - app_server_html:/usr/share/nginx/html
    networks:
      - private_network
    depends_on:
      - load_balancer

  app_server2:
    build:
      context: ./app_server2
    volumes:
      - app_server_html:/usr/share/nginx/html
    networks:
      - private_network
    depends_on:
      - load_balancer

networks:
  private_network:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

volumes:
  app_server_html:
    external: false