# Imagen base
FROM node:14

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos de la aplicación
COPY package.json package-lock.json ./
COPY server.js ./
COPY index.html ./
COPY docker-entrypoint.sh /docker-entrypoint.sh

# Instalar las dependencias
RUN npm install
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

# Puerto en el que la aplicación estará expuesta
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["node", "server.js"]
